version: "3.9"

services:
  currencyservice:
    container_name: currencyservice
    build: .
    ports:
      - "7000:7000"
    env_file:
      - .env

networks:
  default:
    name: nginx_network
    external: true
