apiVersion: v1
kind: Service
metadata:
  labels:
    app: currencyservice-service
  name: currencyservice
spec:
  ports:
    - name: 7000-7000
      port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    app: currencyservice
  type: ClusterIP
status:
  loadBalancer: {}
